server:
  address:     ":39013"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  serverRoot: "resource/public"               # 静态文件服务的目录根路径，配置时自动开启静态文件服务。
  DumpRouterMap: false                        # 是否在Server启动时打印所有的路由列表。
  logPath: "resource/log/server"              # 服务日志保存路径
  errorLogPattern: "error/{Y-m-d}.log"        # 异常错误日志文件格式。默认为"error-{Ymd}.log"
  accessLogEnabled: true                      # 是否记录访问日志。默认为false
  accessLogPattern: "access/{Y-m-d}.log"      # 访问日志文件格式。默认为"access-{Ymd}.log"
# PProf配置
  pprofEnabled: true                          # 是否开启PProf性能调试特性。默认为false
  pprofPattern: "/pprof"                      # 开启PProf时有效，表示PProf特性的页面访问路径，对当前Server绑定的所有域名有效。

#缓存
cache:
  adapter: "redis"                            # 缓存驱动方式，支持：memory|redis|file，不填默认memory

redis:
  default:
    address: "127.0.0.1:6379"
    db: "0"
    pass: ""
    idleTimeout: "20"

database:
  logger:
    path: "logs/database"                     # 日志文件路径。默认为空，表示关闭，仅输出到终端
    stdout: true
  default:
    link: "mysql:root:123456@tcp(127.0.0.1:3306)/sleep?loc=Local&parseTime=true"

# 统一默认日志配置
logger:
  level: "all"                                # 日志级别。可选：all|debu|info|warn|erro|fatal，默认为all
  file: "{Y-m-d}.log"                         # 日志文件格式。默认为"{Y-m-d}.log"
  stdoutColorDisabled: false                  # 关闭终端的颜色打印。可选：false|true，默认false
  rotateExpire: "7d"                          # 日志保留天数
  rotateBackupCompress: 3                     # 日志文件压缩级别，0-9,9最高