// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"sleep-service/internal/dao/internal"
)

// adminAccountDao is the data access object for the table admin_account.
// You can define custom methods on it to extend its functionality as needed.
type adminAccountDao struct {
	*internal.AdminAccountDao
}

var (
	// AdminAccount is a globally accessible object for table admin_account operations.
	AdminAccount = adminAccountDao{internal.NewAdminAccountDao()}
)

// Add your custom methods and functionality below.
