// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"sleep-service/internal/dao/internal"
)

// onlineLogDao is the data access object for the table online_log.
// You can define custom methods on it to extend its functionality as needed.
type onlineLogDao struct {
	*internal.OnlineLogDao
}

var (
	// OnlineLog is a globally accessible object for table online_log operations.
	OnlineLog = onlineLogDao{internal.NewOnlineLogDao()}
)

// Add your custom methods and functionality below.
